//! Bake a document into a Godot scene, by generating a GDScript builder.
//!
//! glTF carries geometry, materials, and animation, but it cannot express
//! *script attachment* — binding a `.gd` to a node is a Godot-native resource
//! edit. That is the one authoring gap the interchange format leaves open.
//!
//! The fix is to emit code the editor already understands rather than to
//! bridge into the editor. The generated script loads the glTF Aurum wrote,
//! attaches scripts by node path, and saves a real `.tscn`. Godot owns the
//! resource format, so nothing here hand-writes one — and the result is a
//! version-controllable scene file with full editor undo.
//!
//! It is also the reason Blender stays optional: the whole chain is
//! Rust -> glTF -> Godot, with no third-party code and no live editor bridge.

use crate::Document;

/// Bind a script to a node in the baked scene.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScriptAttachment {
    /// Node path relative to the scene root, e.g. `Hero` or `Hero/Orb`.
    pub node: String,
    /// A `res://` path to the script.
    pub script: String,
}

/// How to bake.
#[derive(Debug, Clone)]
pub struct BakeOptions {
    /// `res://` path of the glTF this scene is built from.
    pub gltf_path: String,
    /// `res://` path the `.tscn` is written to.
    pub output_scene: String,
    /// Name for the instantiated root node.
    pub root_name: String,
    /// Scripts to attach after instantiating.
    pub scripts: Vec<ScriptAttachment>,
}

impl BakeOptions {
    pub fn new(gltf_path: impl Into<String>, output_scene: impl Into<String>) -> Self {
        Self {
            gltf_path: gltf_path.into(),
            output_scene: output_scene.into(),
            root_name: "Scene".to_string(),
            scripts: Vec::new(),
        }
    }

    pub fn with_root_name(mut self, name: impl Into<String>) -> Self {
        self.root_name = name.into();
        self
    }

    /// Attach a script to a node path.
    pub fn attach(mut self, node: impl Into<String>, script: impl Into<String>) -> Self {
        self.scripts.push(ScriptAttachment {
            node: node.into(),
            script: script.into(),
        });
        self
    }
}

/// Problems that would make a bake fail or produce a broken scene.
pub fn validate(options: &BakeOptions) -> Vec<String> {
    let mut problems = Vec::new();

    if options.gltf_path.trim().is_empty() {
        problems.push("gltf_path must not be empty".into());
    }
    if options.output_scene.trim().is_empty() {
        problems.push("output_scene must not be empty".into());
    }
    if !options.output_scene.ends_with(".tscn") {
        problems.push(format!(
            "output_scene should end in .tscn, got '{}'",
            options.output_scene
        ));
    }
    if options.root_name.trim().is_empty() {
        problems.push("root_name must not be empty".into());
    }
    if options.root_name.contains(['/', '"', '\'']) {
        problems.push(format!(
            "root_name '{}' contains a character Godot node names cannot hold",
            options.root_name
        ));
    }

    for attachment in &options.scripts {
        if attachment.node.trim().is_empty() {
            problems.push("a script attachment has an empty node path".into());
        }
        if !attachment.script.starts_with("res://") {
            problems.push(format!(
                "script '{}' must be a res:// path",
                attachment.script
            ));
        }
    }

    problems
}

/// Escape a string for a GDScript double-quoted literal.
fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Node paths and res:// paths are ASCII in practice; anything
            // unusual is escaped as a codepoint so the literal stays valid.
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Generate the GDScript that bakes the scene.
///
/// The script extends `SceneTree` so it runs both from the editor and
/// headlessly via `godot --headless --script res://bake.gd`, which is what
/// makes the result testable rather than merely generated.
pub fn bake_scene(document: &Document, options: &BakeOptions) -> String {
    let mut script = String::new();

    script.push_str("# Generated by aurum-content. Do not edit by hand.\n");
    script.push_str("#\n");
    script.push_str(&format!(
        "# Source document : {}\n",
        if document.name.is_empty() {
            "(unnamed)"
        } else {
            &document.name
        }
    ));
    script.push_str(&format!(
        "# Contents        : {} meshes, {} materials, {} nodes, {} animations\n",
        document.meshes.len(),
        document.materials.len(),
        document.scene.len(),
        document.animations.len()
    ));
    script.push_str("#\n");
    script.push_str("# Run it from the Godot editor, or headlessly:\n");
    script.push_str(&format!(
        "#   godot --headless --script {}\n",
        options.output_scene.replace(".tscn", ".gd")
    ));
    script.push('\n');
    script.push_str("extends SceneTree\n\n");

    script.push_str(&format!(
        "const SOURCE_SCENE := \"{}\"\n",
        escape(&options.gltf_path)
    ));
    script.push_str(&format!(
        "const OUTPUT_SCENE := \"{}\"\n",
        escape(&options.output_scene)
    ));
    script.push_str(&format!(
        "const ROOT_NAME := \"{}\"\n\n",
        escape(&options.root_name)
    ));

    script.push_str("## Node path -> script path to attach after instantiating.\n");
    script.push_str("const SCRIPT_ATTACHMENTS := {\n");
    for attachment in &options.scripts {
        script.push_str(&format!(
            "\t\"{}\": \"{}\",\n",
            escape(&attachment.node),
            escape(&attachment.script)
        ));
    }
    script.push_str("}\n\n");

    script.push_str(
        r#"func _initialize() -> void:
	var failures := 0

	var packed := load(SOURCE_SCENE) as PackedScene
	if packed == null:
		push_error("[aurum] cannot load " + SOURCE_SCENE)
		quit(1)
		return

	var root := packed.instantiate()
	root.name = ROOT_NAME

	for node_path in SCRIPT_ATTACHMENTS:
		var target := root.get_node_or_null(NodePath(node_path))
		if target == null:
			push_error("[aurum] no node at '" + node_path + "' to attach a script to")
			failures += 1
			continue
		var script := load(SCRIPT_ATTACHMENTS[node_path])
		if script == null:
			push_error("[aurum] cannot load script " + SCRIPT_ATTACHMENTS[node_path])
			failures += 1
			continue
		target.set_script(script)
		print("[aurum] attached ", SCRIPT_ATTACHMENTS[node_path], " to ", node_path)

	if failures > 0:
		push_error("[aurum] %d attachment(s) failed; not writing a partial scene" % failures)
		root.free()
		quit(1)
		return

	var baked := PackedScene.new()
	var pack_error := baked.pack(root)
	if pack_error != OK:
		push_error("[aurum] pack failed with code %d" % pack_error)
		root.free()
		quit(1)
		return

	var save_error := ResourceSaver.save(baked, OUTPUT_SCENE)
	if save_error != OK:
		push_error("[aurum] saving " + OUTPUT_SCENE + " failed with code %d" % save_error)
		root.free()
		quit(1)
		return

	print("[aurum] wrote ", OUTPUT_SCENE)
	root.free()
	quit(0)
"#,
    );

    script
}

/// A default output path for a bake, derived from the document.
pub fn default_bake_path(document: &Document, gltf_path: &str) -> String {
    let stem = gltf_path
        .rsplit('/')
        .next()
        .unwrap_or("scene")
        .trim_end_matches(".gltf")
        .trim_end_matches(".glb");
    let stem = if stem.is_empty() { "scene" } else { stem };
    let _ = document;
    format!("res://{stem}.tscn")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh::box_mesh;
    use crate::scene::Material;

    fn sample() -> Document {
        let mut document = Document::new("level");
        let mesh = document.add_mesh(box_mesh(1.0, 1.0, 1.0));
        let material = document.add_material(Material::gold());
        let root = document.scene_mut().add_node("Root");
        {
            let node = document.scene_mut().node_mut(root).unwrap();
            node.mesh = Some(mesh);
            node.material = Some(material);
        }
        let child = document.scene_mut().add_child(Some(root), "Orb");
        document.scene_mut().node_mut(child).unwrap().mesh = Some(mesh);
        document
    }

    #[test]
    fn generated_script_is_structurally_complete() {
        let options = BakeOptions::new("res://level.gltf", "res://level.tscn")
            .with_root_name("Level")
            .attach("Root/Orb", "res://scripts/orb.gd");

        let script = bake_scene(&sample(), &options);

        assert!(script.starts_with("# Generated by aurum-content."));
        assert!(
            script.contains("extends SceneTree"),
            "must be runnable headlessly"
        );
        assert!(script.contains("const SOURCE_SCENE := \"res://level.gltf\""));
        assert!(script.contains("const OUTPUT_SCENE := \"res://level.tscn\""));
        assert!(script.contains("const ROOT_NAME := \"Level\""));
        assert!(script.contains("\"Root/Orb\": \"res://scripts/orb.gd\""));

        // Every call that can fail must be checked, or a bake silently
        // produces a scene missing its scripts.
        assert!(script.contains("if packed == null"));
        assert!(script.contains("if pack_error != OK"));
        assert!(script.contains("if save_error != OK"));
        assert!(script.contains("quit(1)"));
        assert!(script.contains("quit(0)"));

        // Balanced braces and parentheses, since this is code.
        assert_eq!(
            script.matches('{').count(),
            script.matches('}').count(),
            "unbalanced braces in generated script"
        );
        assert_eq!(
            script.matches('(').count(),
            script.matches(')').count(),
            "unbalanced parentheses in generated script"
        );
    }

    #[test]
    fn generated_script_records_what_the_document_held() {
        let options = BakeOptions::new("res://a.gltf", "res://a.tscn");
        let script = bake_scene(&sample(), &options);
        // The header states the contents, so a stale bake is obvious.
        assert!(
            script.contains("1 meshes, 1 materials, 2 nodes, 0 animations"),
            "header did not describe the document:\n{script}"
        );
    }

    #[test]
    fn attachments_are_emitted_in_order() {
        let options = BakeOptions::new("res://a.gltf", "res://a.tscn")
            .attach("A", "res://a.gd")
            .attach("B/C", "res://b.gd")
            .attach("D", "res://c.gd");
        let script = bake_scene(&Document::new("x"), &options);

        let first = script.find("\"A\"").unwrap();
        let second = script.find("\"B/C\"").unwrap();
        let third = script.find("\"D\"").unwrap();
        assert!(
            first < second && second < third,
            "attachments lost their order"
        );
    }

    #[test]
    fn an_empty_attachment_table_is_still_valid() {
        let options = BakeOptions::new("res://a.gltf", "res://a.tscn");
        let script = bake_scene(&sample(), &options);
        assert!(script.contains("const SCRIPT_ATTACHMENTS := {\n}"));
        assert!(validate(&options).is_empty());
    }

    #[test]
    fn a_bake_with_no_attachments_is_valid() {
        // Scripts are optional: geometry-only scenes are the common case.
        assert!(validate(&BakeOptions::new("res://a.gltf", "res://a.tscn")).is_empty());
    }

    #[test]
    fn strings_are_escaped_so_the_literal_stays_valid() {
        let options = BakeOptions::new("res://a.gltf", "res://a.tscn")
            .attach("we\"ird", "res://back\\slash.gd");
        let script = bake_scene(&sample(), &options);

        assert!(
            script.contains(r#""we\"ird""#),
            "quote was not escaped:\n{script}"
        );
        assert!(script.contains(r"back\\slash"), "backslash was not escaped");
        // The table still parses as two balanced literals.
        assert_eq!(script.matches(": \"res://").count(), 1);
    }

    #[test]
    fn validate_catches_the_ways_a_bake_goes_wrong() {
        let mut options = BakeOptions::new("res://a.gltf", "res://a.tscn");
        options.gltf_path = String::new();
        assert!(validate(&options).iter().any(|p| p.contains("gltf_path")));

        let mut options = BakeOptions::new("res://a.gltf", "res://a.txt");
        options.output_scene = "res://a.txt".into();
        assert!(validate(&options).iter().any(|p| p.contains(".tscn")));

        let mut options = BakeOptions::new("res://a.gltf", "res://a.tscn");
        options.root_name = "bad/name".into();
        assert!(validate(&options).iter().any(|p| p.contains("root_name")));

        let options = BakeOptions::new("res://a.gltf", "res://a.tscn").attach("N", "user://x.gd");
        assert!(
            validate(&options).iter().any(|p| p.contains("res://")),
            "a non-res:// script path should be refused"
        );

        let options = BakeOptions::new("res://a.gltf", "res://a.tscn").attach("", "res://x.gd");
        assert!(validate(&options)
            .iter()
            .any(|p| p.contains("empty node path")));
    }

    #[test]
    fn default_output_path_derives_from_the_gltf() {
        let document = Document::new("x");
        assert_eq!(
            default_bake_path(&document, "res://models/level.gltf"),
            "res://level.tscn"
        );
        assert_eq!(default_bake_path(&document, "res://a.glb"), "res://a.tscn");
        assert_eq!(default_bake_path(&document, "res://"), "res://scene.tscn");
    }
}
